language: cpp
branches:
  only:
  - "/^master$/"
  - "/^pre-release$/"
cache: ccache
compiler:
- gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - linux-headers-$(uname -r)
install:
- "[ $CC = gcc ] && export CC=gcc-6 || true"
- "[ $CXX = g++ ] && export CXX=g++-6 || true"
script:
- mkdir -p build && cd build && cmake .. && make
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: qcBkgyvz++voIV385kVzQ7zWKXNpGCNoIbiuqKCZJgsjBff49Un5KwSJ4hRmRlIhP8gJCT2rI8DuMZfLUHo4vjG44mBnOyi4hJZvQKHz4gbqgQlKGaU2unHK8OXAxxu5JPuPvil6sRBwFwDTtUwNMSOxG41XBle3+N8np3TDh0yiopkFLuncN7OujUAPSDJGRkIkcT39vI1I9PqYwLgqsZinFO6GDGyXmk75KnJa+3CiqlWnvvTE2wnexHrjX7ZmY0BNyALjNOVuWnzdeBy1oqWdrIeYCOpocBHrnqvqQBEGjB8dwcjXb+7sVu5Y/elb0CdWUPAomuULz3qagxejrqaUzKhNmhpfiU2xYBpFvMRV81E10BuAqjCCuxPOCHHxHiyEe7pWqd98nyYUe27Qw5OPKH4+Xii7BHDXgvcWHEBv6W/ldFEIL8zLCNb/RgI1Mm+xTLsYl+NkV+S/ks00bQKKyyNU8WLjona+QhmymoVH7AeueDfuggDbl27XsnO/iVokD8BGuUZG0AgAXC6/PFspJ79SlE7SE5qqrqXDpyfHSlSOlWW4uVghlTwLKqe9VY4ckcPM29OJhvbStv0fLk3c92wwhUEAVTK10RNNB8D5g48W8gAs2ZlnKe/A6MJ9VLENvVObVFFm7zf1lSldfEIUJY/sOacmHj1LgEHB4Qk=
